language: ruby
cache: bundler
bundler_args: --without console
script:
  - bundle exec rake spec
  - RAILS_ENV=production bundle exec rspec --tag production_env
rvm:
  - 2.6.1
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - truffleruby
matrix:
  allow_failures:
    - rvm: truffleruby
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
